# This is a basic workflow to help you get started with Actions

name: CI
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/buildi
on:
  workflow_dispatch:
  push:
    branches:
      - "**"
#  schedule:
#    - cron: '0 15 * * *'

jobs:
  build-and-test:

    name: Build and run external API-tests

    runs-on: self-hosted
#      ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
